# Generated by Django 3.2.13 on 2022-07-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reparo', '0001_initial'),
        ('erecto', '0001_initial'),
        ('accio', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('activated', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sample_amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('algorithm_parameters', models.JSONField(blank=True, default=dict)),
                ('analysis_parameters', models.JSONField(blank=True, default=dict)),
                ('config_parameters', models.JSONField(blank=True, default=dict)),
                ('expected_result', models.JSONField(blank=True, default=dict)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accio.cartridge')),
                ('eluent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erecto.eluent')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erecto.matrix')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
                ('sample_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erecto.unit')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('activated', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('concentration', models.DecimalField(decimal_places=6, max_digits=12)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substances', to='flagrate.case')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accio.compound')),
                ('conc_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erecto.concunit')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization')),
            ],
            options={
                'verbose_name': 'substance',
                'verbose_name_plural': 'substances',
            },
        ),
        migrations.CreateModel(
            name='DataTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('activated', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
            options={
                'verbose_name': 'data tag',
                'verbose_name_plural': 'data tags',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('activated', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mrzfile', models.FileField(blank=True, default='', max_length=1024, upload_to='uploads/mrzfiles/%Y/%m/%d/%H/%M/%S/')),
                ('data_info', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flagrate.case')),
                ('data_tags', models.ManyToManyField(to='flagrate.DataTag')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparo.device')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization')),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'data',
            },
        ),
    ]
