# Generated by Django 3.2.14 on 2022-07-21 02:25

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('erecto', '0001_initial'),
        ('reparo', '0001_initial'),
        ('accio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrumtag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accio.compound'),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accio.experiment'),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='method_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erecto.methodtype'),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='spectrumtag',
            field=models.ManyToManyField(to='accio.SpectrumTag'),
        ),
        migrations.AddField(
            model_name='quantmethod',
            name='in_std_spectrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_std_spectrum', to='accio.spectrum'),
        ),
        migrations.AddField(
            model_name='quantmethod',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='quantmethod',
            name='target_spectrum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_spectrum', to='accio.spectrum'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accio.compound'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparo.device'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erecto.source'),
        ),
        migrations.AddField(
            model_name='compoundtag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='compound',
            name='compoundtag',
            field=models.ManyToManyField(to='accio.CompoundTag'),
        ),
        migrations.AddField(
            model_name='compound',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='analysis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erecto.analysistype'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='compound',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='accio.Compound'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='compoundtag',
            field=models.ManyToManyField(blank=True, to='accio.CompoundTag'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='quantmethod',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='accio.QuantMethod'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erecto.source'),
        ),
    ]
