#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${MYSQL_USER}" ]; then
    base_mysql_image_default_user='root'
    export MYSQL_USER="${base_mysql_image_default_user}"
fi
export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?charset=utf8mb4"

database_ready() {
python << END
import sys
import MySQLdb

try:
    _db = MySQLdb._mysql.connect(
        host="${MYSQL_HOST}",
        user="${MYSQL_USER}",
        password="${MYSQL_PASSWORD}",
        database="${MYSQL_DATABASE}",
        port=int("${MYSQL_PORT}")
    )
except MySQLdb._exceptions.OperationalError:
    sys.exit(-1)

END
}
until database_ready; do
  >&2 echo 'Waiting for MYSQL to become available...'
  sleep 1
done
>&2 echo 'MYSQL is available'

exec "$@"
